--------------------------------------------------------
--  File created - Perþembe-Ocak-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PERSONEL" 
   (	"SICILNO" NUMBER(*,0), 
	"AD" VARCHAR2(50 BYTE), 
	"SOYAD" VARCHAR2(50 BYTE), 
	"SUBENO" VARCHAR2(50 BYTE), 
	"DURUM" VARCHAR2(50 BYTE), 
	"BASLAMATARIHI" DATE, 
	"DOB" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.PERSONEL
SET DEFINE OFF;
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('160','mesut','guler','bid101','kadrolu',to_date('21/12/2005','DD/MM/RRRR'),to_date('30/01/1988','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('165','ebru','yaðmur','bid102','kadrolu',to_date('15/05/2015','DD/MM/RRRR'),to_date('15/05/1990','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('186','mehmet','kara','bid103','kadrolu',to_date('18/08/2003','DD/MM/RRRR'),to_date('01/01/1987','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('2213','durali','tekin','bid104','sözleþmeli',to_date('12/02/2020','DD/MM/RRRR'),to_date('12/06/2021','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('2280','aysel','azize','bid101','sözleþmeli',to_date('08/09/2020','DD/MM/RRRR'),to_date('18/03/2001','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('111','ahmet ali','ciftci','bid105','kadrolu',to_date('28/12/1990','DD/MM/RRRR'),to_date('13/03/1975','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('125','mehmet','kara','bid106','kadrolu',to_date('11/01/2021','DD/MM/RRRR'),to_date('12/02/1999','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('366','kadri','tarkan','bid105','kadrolu',to_date('14/01/2021','DD/MM/RRRR'),to_date('01/01/2020','DD/MM/RRRR'));
Insert into SYSTEM.PERSONEL (SICILNO,AD,SOYAD,SUBENO,DURUM,BASLAMATARIHI,DOB) values ('300','Yýldýz','Tibet','bid106','kadrolu',to_date('05/01/2021','DD/MM/RRRR'),to_date('15/05/1964','DD/MM/RRRR'));
--------------------------------------------------------
--  DDL for Index SYS_C007361
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007361" ON "SYSTEM"."PERSONEL" ("SICILNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger LOG_TRIGGER_PERSONEL
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."LOG_TRIGGER_PERSONEL" 
AFTER INSERT OR UPDATE OR DELETE 
ON PERSONEL
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
declare
begin
 if inserting then
 INSERT INTO LOGS(LOGTYPE,RELATEDTABLE,RELATEDID,LOGTIME)
VALUES('INSERT','PERSONEL',:NEW.SICILNO,LOCALTIMESTAMP);
elsif updating then
 INSERT INTO LOGS(LOGTYPE,RELATEDTABLE,RELATEDID,LOGTIME)
VALUES('UPDATE','PERSONEL',:OLD.SICILNO,LOCALTIMESTAMP);
 ELSIF deleting THEN
 INSERT INTO LOGS(LOGTYPE,RELATEDTABLE,RELATEDID,LOGTIME)
VALUES('DELETE','PERSONEL',:OLD.SICILNO,LOCALTIMESTAMP);
 END IF;
 END LOG_TRIGGER_PERSONEL;
/
ALTER TRIGGER "SYSTEM"."LOG_TRIGGER_PERSONEL" ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONEL" MODIFY ("AD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONEL" MODIFY ("SOYAD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONEL" MODIFY ("SUBENO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONEL" MODIFY ("DURUM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONEL" ADD PRIMARY KEY ("SICILNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONEL" ADD FOREIGN KEY ("SUBENO")
	  REFERENCES "SYSTEM"."SUBELER" ("SUBENO") ENABLE;
